language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r django_project/requirements.txt

# database configuration
services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script:
  # Django test
  - python django_project/manage.py test